matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "14"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script: npm run build && npm run dist

jobs:
  include:
    - script: echo "Deploying to Github Releases"
    - stage: Github Release
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: dist/Domain Genie-0.1.0-mac.zip
        skip_cleanup: true

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"