# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: npm run build && npm run dist

  build_macos:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: npm run build && npm run dist

workflows:
  version: 2
  build:
    jobs:
      - build_windows
      - build_macos